// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9JO51uqGe5eeWCTglI9PcMWA2hMKazJA',
    appId: '1:576961336943:web:082ac148ff10299ff3df9a',
    messagingSenderId: '576961336943',
    projectId: 'flutter-firebase-login-44e76',
    authDomain: 'flutter-firebase-login-44e76.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-44e76.appspot.com',
    measurementId: 'G-8BHSTDHE2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUcNFr7syymp6MuiiR77M86iSVvC4Erjs',
    appId: '1:576961336943:android:feb55bc5f4f211b7f3df9a',
    messagingSenderId: '576961336943',
    projectId: 'flutter-firebase-login-44e76',
    storageBucket: 'flutter-firebase-login-44e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQPKMuu8u9HESapFRrsSXb2QHn6RHxOM',
    appId: '1:576961336943:ios:5cf5d9c6cd5d1745f3df9a',
    messagingSenderId: '576961336943',
    projectId: 'flutter-firebase-login-44e76',
    storageBucket: 'flutter-firebase-login-44e76.appspot.com',
    androidClientId: '576961336943-c5puhg2bnri09ra0kiumn665ghpd9bfj.apps.googleusercontent.com',
    iosClientId: '576961336943-5o3bcoosdminu9n7l4rokgfpdij98pct.apps.googleusercontent.com',
    iosBundleId: 'com.hafeezarfi.cocktailRecipeGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQPKMuu8u9HESapFRrsSXb2QHn6RHxOM',
    appId: '1:576961336943:ios:15410f59f4c7540cf3df9a',
    messagingSenderId: '576961336943',
    projectId: 'flutter-firebase-login-44e76',
    storageBucket: 'flutter-firebase-login-44e76.appspot.com',
    androidClientId: '576961336943-c5puhg2bnri09ra0kiumn665ghpd9bfj.apps.googleusercontent.com',
    iosClientId: '576961336943-ac9d210k4ra61f52c7jqmm8r8dl6lfec.apps.googleusercontent.com',
    iosBundleId: 'com.hafeezarfi.cocktailRecipeGenerator.RunnerTests',
  );
}
